apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name:  postgres
        image:  postgres:15.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "Pg#123"
        - name: POSTGRES_USER
          value: kubenews
        - name: POSTGRES_DB
          value: kubenews
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - port:  5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: marsdeimos/kube-news:{{TAG}}
        ports:
        - containerPort: 8080
        env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_HOST
            value: "postgres"

---

kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer